<a href="https://colab.research.google.com/github/landy891003/MachineLearning_NBS_SVM/blob/master/NBC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
%matplotlib inline

In [ ]:
import csv
from numpy import genfromtxt

In [ ]:
dataPath='check_all.csv'
data=genfromtxt(dataPath,delimiter=',')
tarPath='check2_all.csv'
target=genfromtxt(tarPath,delimiter=',')

X_train,X_test,y_train,y_test=train_test_split(data,target,test_size=0.3)

#testDataPath='HF_LVEF.csv'
#test_data=genfromtxt(testDataPath,delimiter=',')
#testTarPath='HF2_LVEF.csv'
#test_target=genfromtxt(testTarPath,delimiter=',')

#X_train=data
#y_train=target

#X_test=test_data
#y_test=test_target

In [ ]:
modelg=GaussianNB()
modelg.fit(X_train,y_train)
modelg.predict(X_test)

array([0., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.,
       1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 0.,
       1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1.])

In [ ]:
modelg.predict_proba(X_test)

array([[1.00000000e+00, 0.00000000e+00],
       [3.35855324e-11, 1.00000000e+00],
       [4.69523438e-06, 9.99995305e-01],
       [4.87438344e-05, 9.99951256e-01],
       [6.62072677e-05, 9.99933793e-01],
       [1.00000000e+00, 0.00000000e+00],
       [1.00000000e+00, 0.00000000e+00],
       [9.99647401e-01, 3.52599231e-04],
       [5.15390659e-05, 9.99948461e-01],
       [2.62604487e-05, 9.99973740e-01],
       [1.52679919e-02, 9.84732008e-01],
       [4.79667302e-08, 9.99999952e-01],
       [1.56289929e-07, 9.99999844e-01],
       [2.33599291e-04, 9.99766401e-01],
       [1.99106515e-04, 9.99800893e-01],
       [5.85446638e-05, 9.99941455e-01],
       [6.36119044e-05, 9.99936388e-01],
       [4.03745219e-04, 9.99596255e-01],
       [7.02962541e-03, 9.92970375e-01],
       [9.67418441e-01, 3.25815590e-02],
       [9.87142000e-01, 1.28579996e-02],
       [1.61608760e-06, 9.99998384e-01],
       [3.94942661e-06, 9.99996051e-01],
       [5.36508924e-08, 9.99999946e-01],
       [1.838808

In [ ]:
print('Training Set Score:',modelg.score(X_train,y_train))
print('Test Set Score:',modelg.score(X_test,y_test))

Training Set Score: 0.2851985559566787
Test Set Score: 0.2773109243697479


In [ ]:
modelm=MultinomialNB()
modelm.fit(X_train,y_train)
predict = modelm.predict(X_test)
predict

array([0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0.])

In [ ]:
y_test

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
modelm.predict_proba(X_test)

array([[8.22613286e-01, 1.77386714e-01],
       [2.46508063e-01, 7.53491937e-01],
       [8.94125142e-01, 1.05874858e-01],
       [9.39497006e-01, 6.05029943e-02],
       [9.27639948e-01, 7.23600521e-02],
       [9.99898713e-01, 1.01286936e-04],
       [4.95993434e-01, 5.04006566e-01],
       [9.96955892e-01, 3.04410820e-03],
       [9.47751088e-01, 5.22489118e-02],
       [9.80901695e-01, 1.90983048e-02],
       [9.95219029e-01, 4.78097110e-03],
       [8.35830490e-01, 1.64169510e-01],
       [7.19602842e-01, 2.80397158e-01],
       [9.84648828e-01, 1.53511721e-02],
       [9.86103361e-01, 1.38966387e-02],
       [9.71551971e-01, 2.84480294e-02],
       [9.95166164e-01, 4.83383646e-03],
       [9.95238294e-01, 4.76170564e-03],
       [9.89879062e-01, 1.01209379e-02],
       [9.85345390e-01, 1.46546099e-02],
       [9.93981835e-01, 6.01816470e-03],
       [9.14969705e-01, 8.50302954e-02],
       [9.18008786e-01, 8.19912137e-02],
       [8.50447532e-01, 1.49552468e-01],
       [7.345918

In [ ]:
print('Training Set Score:',modelm.score(X_train,y_train))
print('Test Set Score:',modelm.score(X_test,y_test))

Training Set Score: 0.8194945848375451
Test Set Score: 0.7899159663865546


In [ ]:
modelb = BernoulliNB()
modelb.fit(X_train,y_train)
modelb.predict(X_test)

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0.])

In [ ]:
print('Training Set Score:',modelb.score(X_train,y_train))
print('Test Set Score:',modelb.score(X_test,y_test))

Training Set Score: 0.8375451263537906
Test Set Score: 0.8235294117647058
