<a href="https://colab.research.google.com/github/landy891003/ML_Naive_Bayes_Classifier/blob/master/SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn import datasets
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
%matplotlib inline

In [ ]:
import csv
from numpy import genfromtxt

dataPath='TESTDAT.csv'
data=genfromtxt(dataPath,delimiter=',')
tarPath='TESTTAR.csv'
target=genfromtxt(tarPath,delimiter=',')

X_train=data
y_train=target

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
# X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3, random_state=0)

In [ ]:
dataPath='TRAINDAT.csv'
data=genfromtxt(dataPath,delimiter=',')
tarPath='TRAINTAR.csv'
target=genfromtxt(tarPath,delimiter=',')

X_test=data
y_test=target

In [ ]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

In [ ]:
from sklearn.svm import SVC

In [ ]:
svm = SVC(kernel='poly', probability=True)

In [ ]:
svm.fit(X_train_std,y_train)

SVC(kernel='poly', probability=True)

In [ ]:
svm.predict(X_test_std)

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0.,
       1., 0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1.,
       0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0.,
       1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1.,
       0., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 1., 0.,
       1., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 1.,
       1., 0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0.

In [ ]:
y_test

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0.

In [ ]:
svm.predict_proba(X_test_std)

array([[8.54047650e-01, 1.45952350e-01],
       [6.92003987e-01, 3.07996013e-01],
       [7.00759355e-01, 2.99240645e-01],
       [3.35060860e-01, 6.64939140e-01],
       [6.39713735e-01, 3.60286265e-01],
       [7.27571673e-01, 2.72428327e-01],
       [7.17706278e-01, 2.82293722e-01],
       [6.02988865e-01, 3.97011135e-01],
       [6.71578740e-01, 3.28421260e-01],
       [4.93381212e-01, 5.06618788e-01],
       [3.89715619e-01, 6.10284381e-01],
       [6.91994324e-01, 3.08005676e-01],
       [6.91962545e-01, 3.08037455e-01],
       [2.23363154e-01, 7.76636846e-01],
       [6.92037700e-01, 3.07962300e-01],
       [6.28518823e-01, 3.71481177e-01],
       [2.24923272e-02, 9.77507673e-01],
       [3.50515528e-01, 6.49484472e-01],
       [6.56059769e-01, 3.43940231e-01],
       [5.48399173e-01, 4.51600827e-01],
       [6.98570947e-01, 3.01429053e-01],
       [6.61856976e-01, 3.38143024e-01],
       [5.59446309e-01, 4.40553691e-01],
       [6.92998857e-01, 3.07001143e-01],
       [5.701246

In [ ]:
print('Training Set Score:',svm.score(X_train_std,y_train))
print('Test Set Score:',svm.score(X_test_std,y_test))

Training Set Score: 0.9
Test Set Score: 0.6175710594315246
